### ISSUE TITLE
FileStorage example note: address case sensitive 

### ISSUE THREAD

**Issue by SKALE-jace** [skalenetwork/filestorage.js#199]
to use/access FileStorage path via url, address needs to be all lowercase. The example in the [docs](http://docs.skale.network/filestorage.js/1.0.x/#_reserve_space) should make note of this like this example in the [docs](https://docs.skale.network/develop/deploy-a-website-on-skale#:filestorage.js:index.adoc#_additional_notes)

**Comment by cstrangedk** [comment]
closed by #204
